openapi: 3.0.3
info:
  title: Rythmap API
  description: Written on Ktor by Danila Mityashin. Was influenced by Alexander Pervushin.
  version: 1.0.0
tags:
  - name: Account
    description: Account operations
paths:
    /account/register:
        post:
          tags:
              - Account
          summary: Register new account
          operationId: registerAccount
          requestBody:
              required: true
              content:
                application/json:
                    schema:
                      $ref: '#/components/schemas/AccountRegisterRequest'
          responses:
              '200':
                description: Success
                content:
                    application/json:
                      schema:
                          $ref: '#/components/schemas/AccountRegisterResponseSuccess'

    /account/login:
        post:
          tags:
              - Account
          summary: Login to account
          operationId: loginAccount
          requestBody:
              required: true
              content:
                application/json:
                    schema:
                      $ref: '#/components/schemas/AccountLoginRequest'
          responses:
              '200':
                description: Success
                content:
                    application/json:
                      schema:
                          $ref: '#/components/schemas/AccountLoginResponseSuccess'

    /account/info:
      get:
        tags:
          - Account
        summary: Get account information
        operationId: getAccountInfo
        parameters:
          - name: token
            in: query
            description: Account token
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountInfoResponseSuccess'

    /account/delete:
        delete:
            tags:
              - Account
            summary: Delete account
            operationId: deleteAccount
            parameters:
              - name: login
                in: query
                description: Account login (email or username)
                required: true
                schema:
                  type: string
              - name: password
                in: query
                description: Account password
                required: true
                schema:
                  type: string
                  format: password
            responses:
                '200':
                    description: Success
                    content:
                      application/json:
                        schema:
                          type: object
                          properties:
                            message:
                              type: string
                              example: Account deleted

    /account/change/nickname:
        post:
            tags:
              - Account
            summary: Change account nickname
            operationId: changeNickname
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                      new_nickname:
                        type: string
            responses:
                '200':
                    description: Success
                    content:
                      application/json:
                        schema:
                          type: object
                          properties:
                            message:
                              type: string
                              example: Nickname changed

components:
    schemas:
      AccountRegisterRequest:
          type: object
          properties:
              nickname:
                type: string
              password:
                type: string
                format: password
              email:
                type: string
                format: email
      AccountRegisterResponseSuccess:
          type: object
          properties:
              token:
                type: string
              token_type:
                type: string
                enum:
                  - bearer

      AccountLoginRequest:
          type: object
          properties:
              login:
                type: string
              password:
                type: string
                format: password
      AccountLoginResponseSuccess:
            type: object
            properties:
                token:
                    type: string
                token_type:
                    type: string
                    enum:
                    - bearer

      AccountInfoResponseSuccess:
          type: object
          properties:
            account_id:
              type: string
            token:
              type: string
            nickname:
              type: string
            email:
              type: string
            created_at:
              type: string
              format: date-time